// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260623110022_AddTimeLostTimeDetectToOption")]
    partial class AddTimeLostTimeDetectToOption
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Camera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<int>("Fps")
                        .HasColumnType("integer");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Simulate")
                        .HasColumnType("boolean");

                    b.Property<string>("StreamUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TimeDetect")
                        .HasColumnType("integer");

                    b.Property<int>("TimeLost")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Cameras");
                });

            modelBuilder.Entity("CameraOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaHeight")
                        .HasColumnType("integer");

                    b.Property<int>("AreaWidth")
                        .HasColumnType("integer");

                    b.Property<int>("AreaX")
                        .HasColumnType("integer");

                    b.Property<int>("AreaY")
                        .HasColumnType("integer");

                    b.Property<int>("CameraId")
                        .HasColumnType("integer");

                    b.Property<int>("MaxPlateWidth")
                        .HasColumnType("integer");

                    b.Property<int>("MinPlateWidth")
                        .HasColumnType("integer");

                    b.Property<double>("MinProbability")
                        .HasColumnType("double precision");

                    b.Property<int>("NumberFrameForLose")
                        .HasColumnType("integer");

                    b.Property<bool>("Tracking")
                        .HasColumnType("boolean");

                    b.Property<bool>("UseArea")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CameraId")
                        .IsUnique();

                    b.ToTable("CameraOptions", (string)null);
                });

            modelBuilder.Entity("TrackRecognize", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BestImagePath")
                        .HasColumnType("text");

                    b.Property<double>("BestProbability")
                        .HasColumnType("double precision");

                    b.Property<int>("CameraId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("FirstSeen");

                    b.HasIndex("LeftAt");

                    b.HasIndex("PlateNumber");

                    b.ToTable("RecognizeTracks", (string)null);
                });

            modelBuilder.Entity("CameraOption", b =>
                {
                    b.HasOne("Camera", "Camera")
                        .WithOne("Option")
                        .HasForeignKey("CameraOption", "CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camera");
                });

            modelBuilder.Entity("TrackRecognize", b =>
                {
                    b.HasOne("Camera", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Camera");
                });

            modelBuilder.Entity("Camera", b =>
                {
                    b.Navigation("Option")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
