// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260614132822_AddCameraOption")]
    partial class AddCameraOption
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Camera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Simulate")
                        .HasColumnType("boolean");

                    b.Property<string>("StreamUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cameras");
                });

            modelBuilder.Entity("CameraOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaHeight")
                        .HasColumnType("integer");

                    b.Property<int>("AreaWidth")
                        .HasColumnType("integer");

                    b.Property<int>("AreaX")
                        .HasColumnType("integer");

                    b.Property<int>("AreaY")
                        .HasColumnType("integer");

                    b.Property<int>("CameraId")
                        .HasColumnType("integer");

                    b.Property<int>("MaxWidth")
                        .HasColumnType("integer");

                    b.Property<float>("MinWeight")
                        .HasColumnType("real");

                    b.Property<int>("MinWidth")
                        .HasColumnType("integer");

                    b.Property<int>("NumberFrameForLose")
                        .HasColumnType("integer");

                    b.Property<bool>("Tracking")
                        .HasColumnType("boolean");

                    b.Property<bool>("UseArea")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CameraId")
                        .IsUnique();

                    b.ToTable("CameraOption");
                });

            modelBuilder.Entity("CameraOption", b =>
                {
                    b.HasOne("Camera", "Camera")
                        .WithOne("Option")
                        .HasForeignKey("CameraOption", "CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camera");
                });

            modelBuilder.Entity("Camera", b =>
                {
                    b.Navigation("Option")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
