// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260614123931_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Camera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OptionId")
                        .HasColumnType("integer");

                    b.Property<bool>("Simulate")
                        .HasColumnType("boolean");

                    b.Property<string>("StreamUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OptionId");

                    b.ToTable("Cameras");
                });

            modelBuilder.Entity("Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaHeight")
                        .HasColumnType("integer");

                    b.Property<int>("AreaWidth")
                        .HasColumnType("integer");

                    b.Property<int>("AreaX")
                        .HasColumnType("integer");

                    b.Property<int>("AreaY")
                        .HasColumnType("integer");

                    b.Property<int>("MaxWidth")
                        .HasColumnType("integer");

                    b.Property<float>("MinWeight")
                        .HasColumnType("real");

                    b.Property<int>("MinWidth")
                        .HasColumnType("integer");

                    b.Property<int>("NumberFrameForLose")
                        .HasColumnType("integer");

                    b.Property<bool>("Tracking")
                        .HasColumnType("boolean");

                    b.Property<bool>("UseArea")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Option");
                });

            modelBuilder.Entity("Camera", b =>
                {
                    b.HasOne("Option", "Option")
                        .WithMany()
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Option");
                });
#pragma warning restore 612, 618
        }
    }
}
